### ISSUE TITLE
Setting the values with method set_by_int() not working

### ISSUE THREAD

**Issue by CodeJP97** [2kofawsome/pi74HC595#1]
Hi!

First of all, thank you very much for programming this. It's a really nice piece of code.
From my usage I found out, that I cannot use the set_by_int() method and I already figured out why:
In the _set_values method you check for an integer, but the set_by_int() method returns a string and this then evaluates to false (using python 3.7 and 3.8). You could repair this by using pythons map() method. [Python Map](https://stackoverflow.com/questions/7368789/convert-all-strings-in-a-list-to-int)
So to make it in the set_by_int():
`self._set_values(list(map(int, bin(value)[2:])))`
I hope this does the job
Kind regards

**Comment by 2kofawsome** [comment]
Thanks, not sure how I missed you opening this issue. Fixed now
