### ISSUE TITLE
Problem with RPI package

### ISSUE THREAD

**Issue by crlsmtzprds** [2kofawsome/pi74HC595#2]
Everything is fine until we try to load your little demo

```
from pi74HC595 import pi74HC595
import RPi.GPIO as gpio

...
```
When the Pico try to load pi74HC595 it crash with this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/pi74HC595/__init__.py", line 1, in <module>
  File "/lib/pi74HC595/pi74HC595.py", line 1, in <module>
ImportError: no module named 'RPi'
```

So, how can I install RPI package? Or what can I do?

I load manually pi74HC595 and "RPi.GPIO" packages to the Pico, before that I had the error message **ImportError: no module named 'pi74HC595'** but it disappear after load pi74HC595 folder package BUT with folder RPi.GPIO is not working and appears the error message of the top

worth it to say that I'm using Mac OS... and this is a screenshot from my project

<img width="1243" alt="Captura de pantalla 2021-07-14 a la(s) 22 09 37" src="https://user-images.githubusercontent.com/2176151/125722286-eb626b2b-1ef4-420d-8cb8-9bfd8d15be96.png">

**Comment by 2kofawsome** [comment]
Sorry I've never used the Pi Pico/Thonny before so I'm not sure what is causing it. I see the error of no "RPi" is being triggered inside pi74HC595, can you remove the "from pi74HC595..." line and rerun to see if you get the same error.

If you get the error still, then something is wrong with the RPi.GPIO you have downloaded/how you have it set up. If you don't get the import error then it must be pi74HC595's fault.

**Comment by crlsmtzprds** [comment]
Well, I did everything but in the end it did not work ... I will try another ways, but it would not be bad if you bringing us a version that runs on a RB Pico, we will thank you
